---

- name: Download subject public key & add
  apt_key:
    url: https://bintray.com/user/downloadSubjectPublicKey?username=bintray
    state: present

- name: Add kontena.list
  copy:
    content: "deb http://dl.bintray.com/kontena/ubuntu {{ ansible_distribution_release }} main"
    dest: /etc/apt/sources.list.d/kontena.list

- name: Update apt cache
  apt:
    update_cache: yes

- name: Ensure resolvconf is installed.
  package: name=resolvconf state=installed

- name: Install Kontena Agent without interactive mode & postinstall script
  shell: >
    apt-get download kontena-agent \
    && dpkg --unpack kontena-agent*.deb \
    && rm -f /var/lib/dpkg/info/kontena-agent.postinst \
    && dpkg --configure kontena-agent \
    && apt-get install -yf
  args:
    chdir: /tmp # W: Can't drop privileges for downloading as file ...

- name: Setup Master URI inside env file
  lineinfile:
    path: "{{ ka_config_path }}"
    regexp: "^KONTENA_URI="
    line: "KONTENA_URI={{ ka_master_uri }}"

- name: Setup Token inside env file
  lineinfile:
    path: "{{ ka_config_path }}"
    regexp: "^KONTENA_TOKEN="
    line: "KONTENA_TOKEN={{ ka_token }}"

- name: Setup Peer Interface
  lineinfile:
    path: "{{ ka_config_path }}"
    regexp: "^KONTENA_PEER_INTERFACE="
    line: "KONTENA_PEER_INTERFACE={{ ka_peer_interface|default('eth1') }}"

- name: Restart Kontena Agent
  when: ansible_distribution_release == "xenial"
  systemd:
    name: kontena-agent
    daemon_reload: yes
    state: restarted

- name: Restart services
  when: ansible_distribution_release == "trusty"
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - docker
    - kontena-agent
